// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"gitlabee.chehejia.com/k8s/liks-gitops/internal/config"
	"gitlabee.chehejia.com/k8s/liks-gitops/internal/controllers"
	"gitlabee.chehejia.com/k8s/liks-gitops/internal/dal"
	"gitlabee.chehejia.com/k8s/liks-gitops/internal/repo"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*Server, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	query, err := dal.NewQuery(configConfig)
	if err != nil {
		return nil, err
	}
	registry := repo.NewRegistry(query)
	controllersRegistry := controllers.NewRegistry(registry)
	handler := controllers.New(controllersRegistry)
	server := NewServer(ctx, configConfig, handler)
	return server, nil
}
